// GENERATED FILE — PLACEHOLDER.
//
// This file is normally auto-generated by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command connects to YOUR Firebase project and writes the real
// API keys/app IDs below. Do NOT hand-edit this for production — just
// run the command above once you've created a Firebase project, and
// let it overwrite this file.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured yet. Run flutterfire configure.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not configured. Run flutterfire configure.');
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'quick-rewards-REPLACE_ME',
    storageBucket: 'quick-rewards-REPLACE_ME.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'quick-rewards-REPLACE_ME',
    storageBucket: 'quick-rewards-REPLACE_ME.appspot.com',
    iosBundleId: 'com.example.quickRewards',
  );
}
